general {
    disable_loading_bar = true
    grace = 1
    hide_cursor = true
    no_fade_in = false
}

background {
    monitor =
    color = rgba(0, 0, 0, 1.0)
}

input-field {
    monitor =
    size = 320, 52
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.22
    dots_center = true
    outer_color = rgba(57, 186, 230, 0.55)
    inner_color = rgba(13, 16, 23, 0.65)
    font_color = rgba(191, 189, 182, 1.0)
    fade_on_empty = true
    fade_timeout = 0
    placeholder_text = <span foreground="##626a73">password</span>
    hide_input = false
    position = 0, 0
    halign = center
    valign = center
    rounding = 10
    check_color = rgba(57, 186, 230, 0.9)
    fail_color = rgba(240, 113, 120, 0.9)
    fail_text = <i>$FAIL ($ATTEMPTS)</i>
    fail_transition = 300
    capslock_color = rgba(230, 180, 80, 0.9)
}
