hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", 24)
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("GDK_SCALE", 1)
hl.env("GDK_DPI_SCALE", 1)
hl.env("QT_SCALE_FACTOR", 1)
hl.env("XCURSOR_SIZE", 28)
